#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" | tee /var/www/html/index.html
service nginx start
