#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that configures a new Ubuntu machine to respect ...
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
service nginx start
