#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Redirection
apt-get -y update
apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# ufw allow 'OpenSSH'
# ufw allow ssh
# ufw allow 22
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/tecnoayuda.co permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
service nginx restart
