#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Configure your Nginx server to have a custom 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "30i \\\trewrite ^/redirect_me https://tecnoayuda.co permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my404page.html
sudo sed -i "30i \\\terror_page 404 /my404page.html;\n\tlocation = /my404page.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
