#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "30i \\\trewrite ^/redirect_me https://tecnoayuda.co permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my404page.html
sudo sed -i "30i \\\terror_page 404 /my404page.html;\n\tlocation = /my404page.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo sed -i "53i \\\t\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
