#!/usr/bin/env bash
# Task 1. Let us in!
mysql -uroot -p
CREATE USER IF NOT EXISTS 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
exit
mysql -uholberton_user -p -e "SHOW GRANTS FOR 'holberton_user'@'localhost'"
