#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that displays the PID, along with the process name,
# of processes whose name contain the word bash.
pgrep -l bash
