#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that displays To infinity and beyond indefinitely.
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
