#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
trap "echo I am invincible!!!" 15
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
