#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
# You must use the while loop (for and until are forbidden)
# You must use the if statement
i=0
while ((i < 10))
do
echo "holberton School"
if ((i == 8))
then
echo "Hi"
fi
let $((i++))
done
