#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# You must use the while loop (for and until are forbidden)
i=0
while ((i < 13))
do
	j=1
	echo "Hour: $i"
	while ((j < 60))
	do
		echo $j
		let $((j++))
	done
	let $((i++))
done
