#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# You must use the for loop (while and until are forbidden)
# Do not display hidden files
my_list=$(ls)
for i in $my_list
do
	echo "$i" | cut -d- -f2
done
