#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that configures an Ubuntu server with x  requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
