#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ifconfig | grep 'inet addr:' | cut -d : -f 2 | cut -d ' ' -f 1
